language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libfftw3-dev cfitsio-dev libjack-jackd2-dev
script: make
branches:
  only:
    - master
    - dev
notifications:
  recipients:
    - jan.milik@gmail.com
  email:
    on_success: change
    on_failure: always
os:
  - linux
